on:
  workflow_dispatch:
    inputs:
      account:
        description: "Instagram account stored in repository secrets"
        required: true
        default: "PIERREMINIGGIO"
      video_url:
        description: "Video URL"
        required: true
        default: "https://storage.miniggiodev.fr/test/story.mp4"
      proxy:
        description: "Proxy"
        required: true
        default: "http://toulouse.ggio.fr:808"

name: Upload Story
jobs:
  get:
    name: Upload Story
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8']
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-python@v2
      - run: echo $account
        env:
          account: ${{ github.event.inputs.account }}
      - run: sudo apt update
      - run: pip install instagrapi moviepy Pillow
      - run: python main.py $username $password $video_url $proxy > upload.json
        env:
          username: ${{ secrets.USERNAME_PIERREMINIGGIO }}
          password: ${{ secrets.PASSWORD_PIERREMINIGGIO }}
          video_url: ${{ github.event.inputs.video_url }}
          proxy: ${{ github.event.inputs.proxy }}
      - uses: actions/upload-artifact@v2
        with:
          name: upload.json
          path: upload.json
